fix: enable run_command_targets support for target
terraform-aws-modules/terraform-aws-eventbridge pull request #54
Opened 2022-06-21 14:10 UTC by v-starodubov

## Description
- [ ] Remove boolean value inside dynamic "run_command_targets" for_each checker and made it usable for inputs.

## Motivation and Context
- [ ] AWS-RunShellScript event target requires that block for resource creating.
- [ ] https://github.com/terraform-aws-modules/terraform-aws-eventbridge/issues/48

## Breaking Changes
- [ ] None.

2022-06-21 19:55 UTC, antonbabenko requested changes
Almost great.

2022-06-21 19:55 UTC, antonbabenko commented on main.tf
> +    for_each = lookup(each.value, "run_command_targets", null) != null ? [
```suggestion
    for_each = try([each.value.run_command_targets], [])
```
Is shorter

2022-06-23 13:59 UTC, antonbabenko requested changes
Please remove line 76, 77. (Or run example code to see it fail)

2022-06-23 14:12 UTC, v-starodubov commented
Thanks for pointing out the error, missed that when merging your suggestions through the browser.

2022-06-23 15:31 UTC, antonbabenko approved these changes
Lgtm (if it works)

2022-06-23 15:31 UTC, merged

2022-06-23 15:32 UTC, antonbabenko commented
This PR is included in version 1.14.1 :tada: