feat: add discover schema
terraform-aws-modules/terraform-aws-eventbridge pull request #60
Opened 2022-08-08 23:06 UTC by kejvi-doko

## Description
Add default event bus schema discoverer. 

## Motivation and Context
This is change is required since the event bus will not initialised after creation.

## Breaking Changes
No breaking changes

## How Has This Been Tested?
- [ ] I have executed `pre-commit run -a` on my pull request

2022-08-26 02:59 UTC, svenlito commented on variables.tf
> +  description = "Disoverer default schema description"
```suggestion
  description = "Discover default schema description"
```

2022-09-18 01:13 UTC, svenlito approved these changes

2022-09-18 07:43 UTC, antonbabenko requested changes

2022-09-18 07:43 UTC, antonbabenko commented on main.tf
> +  source_arn  = aws_cloudwatch_event_bus.this[0].arn
Add count like on line 35, too

2022-10-24 11:20 UTC, jsecchiero commented
i would like to use this, there are any blockers that are not mentioned in this PR?

2022-10-28 10:58 UTC, closed without merging

2022-10-28 10:59 UTC, antonbabenko commented
This issue has been resolved in version 1.16.0 :tada: